version: '3.8'

services:
  # MQTT Broker with authentication
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: git-friends-mqtt-prod
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/mosquitto.prod.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/passwd:/mosquitto/config/passwd
      - ./docker/mosquitto/acl:/mosquitto/config/acl
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped
    networks:
      - git-friends-network

  # Git Friends Server
  git-friends-server:
    build: .
    container_name: git-friends-server-prod
    ports:
      - "8080:8080"
    volumes:
      - ./docker/config/git-friends.prod.toml:/app/config/git-friends.toml:ro
      - git-friends-logs:/app/logs
    environment:
      - RUST_LOG=info
      - GIT_FRIENDS_CONFIG=/app/config/git-friends.toml
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - git-friends-network
    command: ["./bin/gf-server", "--bind", "0.0.0.0:8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Git Friends IRC Client
  git-friends-irc:
    build: .
    container_name: git-friends-irc-prod
    volumes:
      - ./docker/config/git-friends.prod.toml:/app/config/git-friends.toml:ro
      - git-friends-logs:/app/logs
    environment:
      - RUST_LOG=info
      - GIT_FRIENDS_CONFIG=/app/config/git-friends.toml
    depends_on:
      - mqtt
      - git-friends-server
    restart: unless-stopped
    networks:
      - git-friends-network
    command: ["./bin/gf-irc"]

  # Reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: git-friends-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - git-friends-server
    restart: unless-stopped
    networks:
      - git-friends-network
    profiles:
      - production

networks:
  git-friends-network:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log:
  git-friends-logs:
